### ISSUE TITLE
As a Game Master, I'll be able to search tracks by artist name, album name and genre

### ISSUE THREAD

**Issue by annagabriel-hash** [lea927/drop-that-beat#16]
## User Story

As a Game Master, I'll be able to search tracks by artist name, album name and genre

## Acceptance Criteria

- [x] #17
- [x] #40 
- [x] #18
- [x] #20
- [x] #19
- [x] Given that I'm a registered user, when I go to the room page, enter the track and click search, the system should generate the preview track list.
- [x] Given that I'm a registered user, when I go to the room page, enter an inexistent track  and click search, the system should generate an error message that the track is invalid.
- [x] Given that I'm a registered user, when I go to the room page and (blank track) click search, the system should generate an error message to fill in the blanks

**Comment by annagabriel-hash** [comment]
### Saving tracks to db
@lea927 / @yvettetan not sure with this. At what point do we save the track in the db? After searching or upon clicking add song? 
If we save the track after searching, we'll be able to limit the API calls.
If we save the track after clicking **"Add Song"**, we'll be reducing data stored.
![image](https://user-images.githubusercontent.com/79251819/133222887-c9533d3a-5748-46c1-8848-d03baf0636db.png)

**Comment by lea927** [comment]
> ### Saving tracks to db
> @lea927 / @yvettetan not sure with this. At what point do we save the track in the db? After searching or upon clicking add song?
> If we save the track after searching, we'll be able to limit the API calls.
> If we save the track after clicking **"Add Song"**, we'll be reducing data stored.
> ![image](https://user-images.githubusercontent.com/79251819/133222887-c9533d3a-5748-46c1-8848-d03baf0636db.png)

After clicking "Add Song"
